rdb/aplic/urls.py
from django.urls import path
from .views import IndexView, ContatoView, parcerias, MeusDadosView, eventos, DoacaoView, registro, EventoDetailView, adicionar_comentario, adicionar_feedback, login_view, logout_view
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("contato/", ContatoView.as_view(), name="contato"),
    path("doacao/", DoacaoView.as_view(), name="doacao"),
    path('registro/', registro, name='registro'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('parcerias/', parcerias, name='pagina_parcerias'),
    path('eventos/', eventos, name='eventos'),
    path('evento/<int:pk>/', EventoDetailView.as_view(), name='evento-detalhes'),
    path('adicionar_feedback/<int:evento_id>/', adicionar_feedback, name='adicionar_feedback'),
    path('adicionar_comentario/<int:imagem_id>/<int:evento_id>/', adicionar_comentario, name='adicionar_comentario'),
    path('meus-dados/', MeusDadosView.as_view(), name='meus_dados'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

rdb/rdb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("aplic.urls"))
]

rdb/aplic/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, User



class Pessoa(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=32, null=True)
    cpf = models.CharField(max_length=14, default='')

class Pessoafisica(Pessoa):

    class Meta:
        verbose_name = 'Pessoa Física'
        verbose_name_plural = 'Pessoas Físicas'

    def __str__(self):
        return (self.cpf)
class Pessoajuridica(Pessoa):
    cnpj = models.CharField(max_length=18)
    razaoSocial = models.CharField(max_length=100)
    nomeFantasia = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Pessoa Jurídica'
        verbose_name_plural = 'Pessoas Jurídicas'

    def __str__(self):
        return f"{self.razaoSocial}, {self.nomeFantasia}"

class Evento(models.Model):
    nomeOrganizador = models.CharField(max_length=30)
    data = models.DateField()
    cep = models.CharField(max_length=9)
    endereco = models.CharField(max_length=50, default='')
    descricao = models.TextField(null=True)
    thumbnail = models.ImageField(upload_to='event_images/', blank=True, null=True)
    class Meta:
        verbose_name = 'Evento'
        verbose_name_plural = 'Eventos'
    def __str__(self):
        return f"{self.nomeOrganizador}, {self.data}"
    
class Feedback(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    texto = models.TextField(max_length=200)
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE, null=True, default=None)
    data_criacao = models.DateTimeField(auto_now_add=True, null=True)
    class Meta:
        verbose_name = 'Feedback'
        verbose_name_plural = 'Feedbacks'
    def __str__(self):
        return f'Feedback por {self.autor} em {self.data_criacao}'
class Imagem(models.Model):
    formato = models.ImageField(upload_to='event_images/', blank=True, null=True)
    legenda = models.CharField(max_length=50)
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE, null=True, default=None)
    class Meta:
        verbose_name = 'Imagem' 
        verbose_name_plural = 'Imagens'
    def __str__(self):
        return (self.legenda)
    
class Parceria(models.Model):
    nome = models.CharField(max_length=100)
    email = models.EmailField(max_length=50)
    telefone = models.CharField(max_length=20)  # Alterado para CharField

    class Meta:
        verbose_name = 'Parceria'
        verbose_name_plural = 'Parcerias'

    def __str__(self):
        return f"{self.nome}, {self.email}, {self.telefone}"

    
class Atracao(models.Model):
    texto = models.TextField(max_length=100, default="")
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE, null=True, default=None)
    class Meta:
        verbose_name = 'Atração'
        verbose_name_plural = 'Atrações'
    def __str__(self):
        return (self.texto) 
class Equipamento(models.Model):
    texto = models.TextField(max_length=100,  default="")
    atracao = models.ForeignKey(Atracao, on_delete=models.CASCADE, null=True, default=None)
    def __str__(self):
        return (self.texto)
    class Meta:
        verbose_name = 'Equipamento'
        verbose_name_plural = 'Equipamentos'
    
class Comentario(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    texto = models.TextField()
    data_publicacao = models.DateTimeField(auto_now_add=True)
    imagem = models.ForeignKey(Imagem, on_delete=models.CASCADE)
    class Meta:
        verbose_name = 'Comentário'
        verbose_name_plural = 'Comentários'
    def __str__(self):
        return f'Comentario por {self.autor} em {self.data_publicacao}'

class Doacao(models.Model):
    valor = models.IntegerField()
    doador = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    item = models.TextField(max_length=100)
    class Meta:
        verbose_name = 'Doação'
        verbose_name_plural = 'Doações'

rdb/aplic/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Feedback

class UserCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['texto']

rdb/aplic/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView
from .forms import FeedbackForm
from .models import Evento, Feedback, Imagem, Comentario, Parceria, Pessoa
from django.views.decorators.http import require_POST
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.views import View
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
class IndexView(TemplateView):
    template_name = 'index.html'
class GaleriaView(TemplateView):
    template_name = 'galeria.html'
class ContatoView(TemplateView):
    template_name = 'contato.html'
class DoacaoView(TemplateView):
    template_name = "doacao.html"

class RegistroView(TemplateView):
    template_name = 'registro.html'
class ParceriasView(TemplateView):
    template_name = 'parcerias.html'
class EventosView(TemplateView):
    template_name = 'eventos.html'

class EventosView(ListView):
    model = Evento
    template_name = 'eventos.html'
    context_object_name = 'eventos'
class EventoDetailView(DetailView):
    model = Evento
    template_name = 'evento_detalhes.html'  # Crie este template posteriormente
    context_object_name = 'evento'


def registro(request):
    if request.method == 'POST':
        nome = request.POST.get("nome")
        cpf = request.POST.get("cpf")
        username = request.POST.get("username")
        password = request.POST.get("senha")

        # Verifique se o campo 'username' está definido
        if username:
            # Verifique se o username já existe
            if User.objects.filter(username=username).exists():
                messages.error(request, 'O nome de usuário já existe. Escolha outro.')
                return redirect('registro')

            # Criação do usuário e pessoa se o username não existir
            user_instance = User.objects.create_user(username=username, password=password)
            pessoa_instance = Pessoa.objects.create(nome=nome, cpf=cpf, user=user_instance)
            user_instance.save()
            pessoa_instance.save()

            # Adiciona uma mensagem de sucesso
            messages.success(request, 'Registro bem-sucedido. Faça login para continuar.')

            return redirect('login')
        else:
            # Adiciona uma mensagem de erro se o campo 'username' não for preenchido
            messages.error(request, "O campo 'username' deve ser preenchido.")
            return redirect('registro')
    else:
        # Lógica para renderizar o formulário HTML
        return render(request, "registro.html")

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('http://127.0.0.1:8000/')  # Redirecione para a página de dashboard ou outra página desejada após o login
    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('index')


def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
@require_POST
def adicionar_feedback(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)

    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            feedback = form.save(commit=False)
            feedback.evento = evento
            feedback.autor = request.user
            feedback.save()

            # Redirecione para a página de detalhes do evento
            return redirect('evento-detalhes', pk=evento_id)
        else:
            return redirect('evento-detalhes', pk=evento_id)
    else:
        form = FeedbackForm()

    feedbacks = Feedback.objects.filter(evento=evento)
    return render(request, 'aplic/adicionar_feedback.html', {'form': form, 'evento': evento, 'feedbacks': feedbacks})


def adicionar_comentario(request, imagem_id, evento_id):
    if request.method == 'POST':
        imagem = get_object_or_404(Imagem, pk=imagem_id)
        texto = request.POST.get('texto')
        autor = request.user
        Comentario.objects.create(imagem=imagem, autor=autor, texto=texto)
        return redirect('evento-detalhes', pk=evento_id)
    else:
        pass

class MeusDadosView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'meusdados.html')
    
def parcerias(request):
    parcerias = Parceria.objects.all()
    return render(request, 'parcerias.html', {'parcerias': parcerias})

def eventos(request):
    search_term = request.GET.get('search', '')
    print(f"Termo de pesquisa: {search_term}")
    eventos = Evento.objects.filter(nomeOrganizador__icontains=search_term)
    return render(request, 'eventos.html', {'eventos': eventos, 'search_term': search_term})

rdb/aplic/templates/contato.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contatos</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 20px;
        }

        .contact-list {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }

        .contact-item {
            background-color: #f0f0f0;
            padding: 20px;
            margin-bottom: 20px;
            width: 100%;
            box-sizing: border-box;
        }

        .contact-item h2 {
            color: #333;
            margin-bottom: 10px;
        }

        .contact-item p {
            color: #666;
            margin-bottom: 10px;
        }

        @media (min-width: 768px) {
            .contact-item {
                width: 48%;
            }
        }
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        .navbar {
            background-color: #333;
            overflow: hidden;
            position: fixed;
            top: 0;
            width: 100%;
        }

        .navbar a {
            color: white;
            float: left;
            display: block;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        .navbar a:hover {
            background-color: #ddd;
            color: black;
        }

        .navbar a.logar {
            float: right;
        }
        .navbar a.registro {
            float: right
        }

        .content {
            padding-top: 60px;
            text-align: center;
        }

        .content h1 {
            font-size: 3em;
            margin-bottom: 0.5em;
        }

        .content p {
            font-size: 1.5em;
            margin-top: 0.5em;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <a href="http://127.0.0.1:8000/">Principal</a>
        <a href="/galeria">Galeria</a>
        <a href="/contato">Contato</a>
        <a href="/parcerias">Parcerias</a>
        <a href="/eventos">Eventos</a>
        <a href="/registro" class="registro">Registrar</a>
        <a href="/login" class="logar">Entrar</a>
    </div>
    <br><br><br>
    <div class="container">
        <h1>Contatos</h1>
        <div class="contact-list">
            <div class="contact-item">
                <h2>Suporte</h2>
                <p>Email: suporte@example.com</p>
                <p>Telef

rdb/aplic/templates/evento_detalhes.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhes do Evento - {{ evento.nomeOrganizador }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
        }

        h1 {
            background: linear-gradient(45deg, #007BFF, #00FFF0);
            color: #fff;
            text-align: center;
            padding: 20px;
            margin: 0;
            font-size: 36px;
            letter-spacing: 2px;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
        }

        .back-button {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            margin: 10px;
            display: inline-block;
            cursor: pointer;
        }

        .back-button:hover {
            background-color: #0056b3;
        }

        h2 {
            font-size: 24px;
            color: #007BFF;
        }

        p {
            margin-bottom: 10px;
        }

        .section {
            border: 1px solid #ccc;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            margin-top: 20px;
        }

        .gallery-container {
            display: flex;
            flex-wrap: wrap;
        }

        .gallery-item {
            flex: 0 0 calc(33.33% - 20px);
            margin: 10px;
            box-sizing: border-box;
        }

        .gallery img {
            cursor: pointer;
            max-width: 100%;
            border: 1px solid #ccc;
            border-radius: 5px;
            transition: transform 0.3s ease-in-out;
        }

        .gallery img:hover {
            transform: scale(1.05);
        }

        .comments {
            display: none;
            background-color: #f0f0f0;
            padding: 20px;
            border-radius: 5px;
            margin-top: 20px;
        }

        .comments p {
            margin: 5px 0;
        }

        .comment-item {
            border-bottom: 1px solid #ccc;
            padding-bottom: 10px;
            margin-bottom: 10px;
        }

        .add-comment-button,
        .add-feedback-button {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            margin-top: 20px;
            display: inline-block;
            margin-right: 10px;
            cursor: pointer;
        }

        .add-comment-button:hover,
        .add-feedback-button:hover {
            background-color: #0056b3;
        }

        #campo-feedback {
            margin-top: 20px;
        }

        #texto-feedback {
            width: 100%;
            margin-bottom: 10px;
        }

        @keyframes pulse {
            0% {
                transform: scale(1);
            }

            50% {
                transform: scale(1.05);
            }

            100% {
                transform: scale(1);
            }
        }

        h1:hover {
            animation: pulse 1s infinite;
        }

        .feedback-section {
            background-color: #fff;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            margin-top: 20px;
        }

        .feedback {
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 10px;
            margin: 10px 0;
        }

    </style>
</head>

<body>

    <h1>{{ evento.nomeOrganizador }}</h1>
    <a href="{% url 'eventos' %}" class="back-button">Voltar</a>

    <div class="section">
        <h2>Detalhes do Evento</h2>
        <p><strong>Data:</strong> {{ evento.data }}</p>
        <p><strong>CEP:</strong> {{ evento.cep }}</p>
        <p><strong>Endereço:</strong> {{ evento.endereco }}</p>
        <p><strong>Descrição:</strong> {{ evento.descricao }}</p>
    </div>

    <div class="section">
        <h2>Atrações</h2>
        <ul>
            {% for atracao in evento.atracao_set.all %}
            <li>{{ atracao.texto }}</li>
            <ul>
                {% for equipamento in atracao.equipamento_set.all %}
                <li>{{ equipamento.texto }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </ul>
    </div>

    <div class="section">
        <h2>Galeria de Imagens</h2>
        <div class="gallery-container">
            {% for imagem in evento.imagem_set.all %}
            <div class="gallery-item">
                <img src="{{ imagem.formato.url }}" alt="{{ imagem.legenda }}" onclick="toggleComments('{{ imagem.id }}')">
                <p>{{ imagem.legenda }}</p>
                <div id="comments_{{ imagem.id }}" class="comments" style="display: none;">
                    {% for comentario in imagem.comentario_set.all %}
                    <div class="comment-item">
                        <p><strong>{{ comentario.autor.username }} </strong> disse em {{ comentario.data_criacao }}:</p>
                        <p>{{ comentario.texto }}</p>
                    </div>
                    {% endfor %}
                    {% if user.is_authenticated %}
                    <form method="post" action="{% url 'adicionar_comentario' imagem.id evento.id %}">
                        {% csrf_token %}
                        <label for="comment_text">Adicionar Comentário:</label>
                        <input type="text" name="texto" id="comment_text">
                        <input type="submit" value="Enviar">
                    </form>
                    {% else %}
                    <p>Faça login para adicionar comentários.</p>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="section feedback-section">
        <h2>Feedbacks</h2>
        <ul>
            {% for feedback in evento.feedback_set.all %}
            <li class="feedback">
                <p><strong>{{ feedback.autor.username }} </strong> disse em {{ feedback.data_criacao }}:</p>
                <p>{{ feedback.texto }}</p>
            </li>
            {% endfor %}
        </ul>
        {% if user.is_authenticated %}
        <form method="post" id="form-feedback" action="{% url 'adicionar_feedback' evento.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="button" class="add-feedback-button" id="mostrar-feedback">Adicionar Feedback</button>
            <div id="campo-feedback" style="display: none;">
                <textarea id="id_texto" name="texto" rows="4" cols="50" placeholder="Digite seu feedback aqui"></textarea>
                <button type="submit">Enviar Feedback</button>
            </div>
        </form>
        {% else %}
        <p>Faça login para adicionar feedbacks.</p>
        {% endif %}
    </div>

    <script>
        document.getElementById('mostrar-feedback').addEventListener('click', function () {
            document.getElementById('campo-feedback').style.display = 'block';
        });

        function toggleComments(imagemId) {
            var commentsDiv = document.getElementById('comments_' + imagemId);
            commentsDiv.style.display = (commentsDiv.style.display === 'none' || commentsDiv.style.display === '') ? 'block' : 'none';
        }
    </script>
</body>

</html>

rdb/aplic/templates/meusdados.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f5f5f5;
            color: #333;
            margin: 0;
            padding: 0;
        }

        h2 {
            background-color: #3498db;
            color: #fff;
            padding: 15px;
            margin: 0;
            text-align: center;
        }

        .user-info {
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }

        .user-info p {
            margin: 10px 0;
        }

        h3 {
            color: #3498db;
        }

        form {
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }

        label, select, input {
            display: block;
            margin-bottom: 15px;
        }

        button {
            padding: 10px;
            background-color: #27ae60;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .camposFisica,
        .camposJuridica {
            display: none;
        }

        /* Estilizando os campos */
        input,
        select,
        button {
            width: 100%;
            padding: 10px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
        }

        button:hover {
            background-color: #219d54;
        }

        /* Adicione mais estilos conforme necessário */

    </style>
</head>

<body>
    <a href="{% url 'eventos' %}" class="back-button">Voltar</a>
    <h2>Meus Dados</h2>

    <div class="user-info">
        <h3>Informações do Usuário</h3>
        <p>Username: {{ user.username }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Telefone: {{ user.pessoa.telefone }}</p>
        {% if user.pessoa.pessoafisica %}
        <p>CPF: {{ user.pessoa.pessoafisica.cpf }}</p>
        {% elif user.pessoa.pessoajuridica %}
        <p>CNPJ: {{ user.pessoa.pessoajuridica.cnpj }}</p>
        <p>Razão Social: {{ user.pessoa.pessoajuridica.razaoSocial }}</p>
        <p>Nome Fantasia: {{ user.pessoa.pessoajuridica.nomeFantasia }}</p>
        {% endif %}
    </div>

    <form method="post">
        {% csrf_token %}

        <label for="id_nome">Nome Completo:</label>
        <input type="text" name="nome" id="id_nome" value="{{ user.pessoa.nome }}" required>

        <label for="id_tipo">Tipo de Pessoa:</label>
        <select name="tipo" id="id_tipo" onchange="mostrarCampos(this.value)" required>
            <option value="" {% if not user.pessoa.pessoafisica and not user.pessoa.pessoajuridica %}selected{% endif %}>Escolha...</option>
            <option value="fisica" {% if user.pessoa.pessoafisica %}selected{% endif %}>Pessoa Física</option>
            <option value="juridica" {% if user.pessoa.pessoajuridica %}selected{% endif %}>Pessoa Jurídica</option>
        </select>

        <div class="camposFisica">
            <label for="id_cpf">CPF:</label>
            <input type="text" name="cpf" id="id_cpf" value="{{ user.pessoa.pessoafisica.cpf }}" required>
        </div>

        <div class="camposJuridica">
            <label for="id_cnpj">CNPJ:</label>
            <input type="text" name="cnpj" id="id_cnpj" value="{{ user.pessoa.pessoajuridica.cnpj }}" required>

            <label for="id_razao_social">Razão Social:</label>
            <input type="text" name="razao_social" id="id_razao_social" value="{{ user.pessoa.pessoajuridica.razaoSocial }}" required>

            <label for="id_nome_fantasia">Nome Fantasia:</label>
            <input type="text" name="nome_fantasia" id="id_nome_fantasia" value="{{ user.pessoa.pessoajuridica.nomeFantasia }}" required>
        </div>

        <button type="submit">Atualizar Dados</button>
    </form>

    <script>
        function mostrarCampos(tipo) {
            var camposFisica = document.querySelector('.camposFisica');
            var camposJuridica = document.querySelector('.camposJuridica');

            if (tipo === 'fisica') {
                camposFisica.style.display = 'block';
                camposJuridica.style.display = 'none';
            } else if (tipo === 'juridica') {
                camposFisica.style.display = 'none';
                camposJuridica.style.display = 'block';
            } else {
                camposFisica.style.display = 'none';
                camposJuridica.style.display = 'none';
            }
        }
    </script>
</body>

</html>

rdb/aplic/templates/registro.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .back-button {
            background-color: rgba(8, 177, 255, 0.534);
            color: #fff;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            margin: 10px;
            display: inline-block;
            cursor: pointer;
            position: absolute;
            top: 10px;
            left: 10px;
        }

        .back-button:hover {
            background-color: #0056b3;
        }

        .container {
            background-color: #ffffff;
            border-radius: 8px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            overflow: hidden;
            width: 300px;
        }

        h2 {
            background-color: rgba(8, 177, 255, 0.534);
            color: #fff;
            padding: 20px;
            text-align: center;
            margin: 0;
        }

        form {
            padding: 20px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .form-group label {
            display: block;
            font-size: 14px;
            margin-bottom: 8px;
        }

        .form-group input {
            width: 100%;
            padding: 10px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 14px;
        }

        .form-group button {
            width: 100%;
            padding: 10px;
            box-sizing: border-box;
            background-color: #3498db;
            color: #fff;
            border: none;
            border-radius: 4px;
            font-size: 16px;
            cursor: pointer;
        }

        .form-group button:hover {
            background-color: rgba(8, 177, 255, 0.534);
        }
    </style>
</head>

<body>
    <a href="{% url 'eventos' %}" class="back-button">Voltar</a>
    <div class="container">
        <h2>Registro</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">Username:</label>
                <input type="text" id="id_username" name="username" required>
            </div>
            <div class="form-group">
                <label for="id_name">nome:</label>
                <input type="text" id="id_name" name="nome" required>
            </div>
            <div class="form-group">
                <label for="id_cpf">CPF:</label>
                <input type="text" id="id_cpf" name="cpf" required>
            </div>
            <div class="form-group">
                <label for="id_password">Password:</label>
                <input type="password" id="id_password" name="senha" required>
            </div>
            <div class="form-group">
                <button type="submit" style="background-color: rgba(8, 177, 255, 0.534)"> Registrar</button>
            </div>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
            </ul>
            {% endif %}
        </form>
    </div>
</body>

</html>